### ISSUE TITLE
Height of the iFrame.

### ISSUE THREAD

**Issue by sjojo** [kasperisager/vanilla-wysihtml5#10]
Hello,

I've come across a little issue. Currently the comment box is 100px. I want to adjust this to 150px, I can do this fine in the Source Editor thing that pops up in Google Chrome when you inspect the element (Not sure what it's really called) However I'd like to do this 'for real' so that my users will benefit from it too. So my question is:

How do I adjust the height of the sandbox iFrame?

Any help would be appriciated. :)

**Comment by kasperisager** [comment]
The editor automatically mirrors the CSS of the original text area. To adjust the height of the editor you will therefore have to adjust the height of the text area. Something like this should do the trick:

```css
textarea.TextBox {
  height: 150px;
  min-height: 150px;
}
```

**Comment by sjojo** [comment]
Thanks for the comment, now on another note. I would like to add that when you clicked a button, say the Bold button that the background turns black to indicate that it's active. I suppose I need to do this with JavaScript, but I'm not sure where to put the JS :/ I already did the above, should've thought of that myself! :P THanks!

**Comment by kasperisager** [comment]
No problem! With regards to the active state of buttons Wysihtml5 does add a `.wysihtml5-command-active`-class that you can target.

**Comment by sjojo** [comment]
Thanks a shit ton! :D

**Comment by kasperisager** [comment]
Pleasure!
