### ISSUE TITLE
Overwrites Vanilla native auto embed features

### ISSUE THREAD

**Issue by alexcroox** [kasperisager/vanilla-wysihtml5#12]
In Vanilla class.format.php it converts any youtube, vimeo etc URLs into embeds. However when pasting in these type of URLs to the comment box with this plugin, it turns them into anchor tags, preventing Vanilla from doing this auto conversion to video object.

**Comment by kasperisager** [comment]
This plugin is just a wrapper for the Wysihtml5 library and at this point I won't be monkey-patching it to improve Vanilla-compatibility; this is all handled much better in the upcoming "Advanced Editor" plugin in Vanilla core.
