### ISSUE TITLE
Getting icons instead of text in the buttons in Vanilla 2.1.11

### ISSUE THREAD

**Issue by rbrahmson** [kasperisager/vanilla-wysihtml5#14]
Hi Kasper,
Please see this discussion: http://vanillaforums.org/discussion/27855/wysihtml5-2-0-1-where-are-the-buttons#latest

Running V2.1.11.  See button text, not icons.
As suggested in the discussion, I copied the resources folder from 2.2 github into my vanilla 2.1.11 (in the right place;-) and then added the following line
$Sender->AddCssFile('vanillicon.css', 'static');
to the Gdn_Form_beforeBodyBox_handler function in class.wysihtml5.plugin.php

All in hope to get the icons instead of the text in the buttons.

Didn't work.

Appreciate any suggestions.

**Comment by kasperisager** [comment]
Closing this as icons as available as of Vanilla 2.2
